from . import klinik_hewan
from . import res_partner
from . import klinik_pelanggan
from . import klinik_janji
from . import product_template
from . import product_product
from . import klinik_ruangan
from . import klinik_dokter
from . import klinik_resep
